# for debugging, saves intermediate pdfs, jpgs
pagesize:
  - 896
  - 896
marginLeft: 20
marginRight: 20
marginTop: 20
marginBottom: 20
forceOnePage: false
autoAdjustHeight: false
savePDF: true
saveImage: true
dpi: 96
overwrite: false
extension: "jpeg"
css: null
css_path: null
